name: relaxury_partner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Device Service Dependencies
  permission_handler: ^6.1.3

  # Presentation Support Dependencies
  shimmer: ^2.0.0
  getwidget: ^2.0.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.5.2
  file_picker: ^3.0.4
  flutter_svg: ^0.22.0
  video_player: ^2.1.12
  image_picker: ^0.8.0+3
  pull_to_refresh: ^2.0.0
  cupertino_icons: ^1.0.0
  dotted_decoration: ^2.0.0
  flutter_form_builder: ^6.0.1
  flutter_staggered_grid_view: ^0.4.0

  # Domain Support Dependencies
  dartz: ^0.10.0-nullsafety.2
  get: ^4.3.4

  # Data Support Dependencies
  http: ^0.13.3
  get_storage: ^2.0.3
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  internet_connection_checker: ^0.0.1+2

  # Dev Ops
  change_app_package_name: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/pages/
    - assets/icons/wallet/
    - assets/icons/service_type/